language: python
python:
  - "2.7"

sudo: false

install:
  - pip install cactus
  - wget https://raw.githubusercontent.com/mozilla/html5-lint/master/html5check.py

script:
  - cactus build
  - CHECK=$(for file in .build/*.html; do python html5check.py -geh $file; done;)
  - if [[ ! -z $(echo "$CHECK" | grep -vE 'iframe') ]]; then echo "$CHECK"; exit 1; fi;
